[package]
name = "epd-gfx"
version = "0.1.0"
edition = "2021"
authors = ["Jens Pfeifle <jens@pfeifle.tech>"]

[dependencies]
embedded-graphics = "0.7.1"
embedded-graphics-core = "0.3.3"
rusttype = "0.9.2"
